apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: voting-app
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
    - containerPort: 80
